// LOBBY
export const LOBBY_FETCH_REALMS = 'LOBBY/FETCH_REALMS';
export const LOBBY_FETCH_REALMS_FULFILLED = 'LOBBY/FETCH_REALMS_FULFILLED';

// REALM
export const REALM_CREATE = 'REALM/CREATE';
export const REALM_CREATE_FULFILLED = 'REALM/CREATE_FULFILLED';
export const REALM_FETCH = 'REALM/FETCH';
export const REALM_FETCH_FULFILLED = 'REALM/FETCH_FULFILLED';
export const REALM_UPDATE_GEOMETRY = 'REALM/UPDATE_GEOMETRY';
export const REALM_UPDATE_GEOMETRY_FULFILLED = 'REALM/UPDATE_GEOMETRY_FULFILLED';
export const REALM_UPDATE_VOXELS = 'REALM/UPDATE_VOXELS';
export const REALM_RESET = 'REALM/RESET';

// USER
export const USER_REFRESH_SESSION = 'USER/REFRESH_SESSION';
export const USER_REFRESH_SESSION_FULFILLED = 'USER/REFRESH_SESSION_FULFILLED';
export const USER_REFRESH_SESSION_REJECTED = 'USER/REFRESH_SESSION_REJECTED';
export const USER_SIGNOUT = 'USER/SIGNOUT';
