// LOBBY
export const LOBBY_FETCH_REALMS = 'LOBBY/FETCH_REALMS';
export const LOBBY_FETCH_REALMS_FULFILLED = 'LOBBY/FETCH_REALMS_FULFILLED';
export const LOBBY_SET_FILTER = 'LOBBY/SET_FILTER';
export const LOBBY_SET_PAGE = 'LOBBY/SET_PAGE';

// REALM
export const REALM_CREATE = 'REALM/CREATE';
export const REALM_CREATE_FULFILLED = 'REALM/CREATE_FULFILLED';
export const REALM_FETCH = 'REALM/FETCH';
export const REALM_FETCH_FULFILLED = 'REALM/FETCH_FULFILLED';
export const REALM_HIDE_METADATA_POPUP = 'REALM/HIDE_METADATA_POPUP';
export const REALM_RESET = 'REALM/RESET';
export const REALM_SHOW_METADATA_POPUP = 'REALM/SHOW_METADATA_POPUP';
export const REALM_UPDATE_FOG = 'REALM/UPDATE_FOG';
export const REALM_UPDATE_GEOMETRY = 'REALM/UPDATE_GEOMETRY';
export const REALM_UPDATE_GEOMETRY_FULFILLED = 'REALM/UPDATE_GEOMETRY_FULFILLED';
export const REALM_UPDATE_METADATA = 'REALM/UPDATE_METADATA';
export const REALM_UPDATE_METADATA_FULFILLED = 'REALM/UPDATE_METADATA_FULFILLED';
export const REALM_UPDATE_VOXELS = 'REALM/UPDATE_VOXELS';

// USER
export const USER_HIDE_SESSION_POPUP = 'USER/HIDE_SESSION_POPUP';
export const USER_REFRESH_SESSION = 'USER/REFRESH_SESSION';
export const USER_REFRESH_SESSION_FULFILLED = 'USER/REFRESH_SESSION_FULFILLED';
export const USER_REFRESH_SESSION_REJECTED = 'USER/REFRESH_SESSION_REJECTED';
export const USER_SHOW_SESSION_POPUP = 'USER/SHOW_SESSION_POPUP';
export const USER_LOGIN = 'USER/LOGIN';
export const USER_LOGIN_FULFILLED = 'USER/LOGIN_FULFILLED';
export const USER_LOGIN_REJECTED = 'USER/LOGIN_REJECTED';
export const USER_REGISTER = 'USER/REGISTER';
export const USER_REGISTER_FULFILLED = 'USER/REGISTER_FULFILLED';
export const USER_REGISTER_REJECTED = 'USER/REGISTER_REJECTED';
export const USER_SIGNOUT = 'USER/SIGNOUT';
